### ISSUE TITLE
Discrete Codes for Power On/Off

### ISSUE THREAD

**Issue by chairstacker** [yahat/broadlink_mini_homeassistant_ir_codes_samsung_tv#2]
Trying to find the discrete codes for 'Power On', 'Power Off', and the various sources for my Samsung Soundbar HW-J450 like you did for the Samsung TVs.

My soundbar remote control only has a 'Power Toggle' key just like the Samsung TV one does.

How did you find the discrete codes for on vs. off, HDMI1 vs. HDMI2 vs. HDMI3?

Thanks,
Chairstacker

**Comment by vladbabii** [comment]
I have an android phone with an IR emitter and tried alot of software from the app store until I found two that had all the functions combined. Another option would be to find and buy on ebay a programming/factory  remote for your soundbar.

**Comment by adrianmihalko** [comment]
Power on doesn't work for me on c series.

**Comment by adrianmihalko** [comment]
I generated code to repeat 5 times and now works:

https://dimagoltsman.github.io/Random-Broadlink-RM-Code-Generator/#
