### ISSUE TITLE
Component input select?

### ISSUE THREAD

**Issue by mindtripper** [yahat/broadlink_mini_homeassistant_ir_codes_samsung_tv#3]
Hi Yahat,

Do you have the IR code for Component input select?
I've just connected my Nintendo WII, and I'd like to automate the selection of the input it uses on my good old Samsung plasma TV.

Any help will be appreciated!

**Comment by mindtripper** [comment]
Answering my own question:

Using this [post](https://community.home-assistant.io/t/configuration-of-broadlink-ir-device-and-getting-the-right-ir-codes/48391/7)

And getting the IR codes [from](http://www.remotecentral.com/cgi-bin/mboard/rc-discrete/thread.cgi?5780)

I was able to generate the Broadlink compatible IR code for Component1:
`JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EjcSEhISEhISEhI3EjcSEhISEjcSNxI3EjcSEhIABfgNBQ==`

**Comment by vladbabii** [comment]
Added to list, thank you!
